### ISSUE TITLE
Can't find Drone via BLE

### ISSUE THREAD

**Issue by ungtu3012** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#11]
I uploaded ***Official release with BLE Remocon - 170318*** to board via STLink with TrueSTUDIO. Then LED 1 and LED 2 off. (I toggled RST button). But can't find Drone in Android app.

![image](https://user-images.githubusercontent.com/33345692/38778007-fc300e5a-40db-11e8-9133-c852fde89183.png)

**Comment by mrka124** [comment]
Me too :((

**Comment by teomaras76** [comment]
Hi,
thanks for the message. Strange this issue never happened before, let me check in details about it.
Please may you kindly try the following:
1) I uploaded before Download directly the binary file for the STM32: https://github.com/STMicroelectronics-CentralLabs/ST_Drone_FCU_F401/tree/master/STM32%20FW%20Project/Official%20release%20with%20BLE%20Remocon%20-%20170318/EWARM/ToyDrone_Configuration/Exe 
You can download the binary file using the STLink Utility: 
http://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-programmers/stsw-link007.html
Please let me know the result with this binary.

2) Please confirm the version of ST Drone Android app you are using.

3) If the binary is correct, the drone should be discoverable as BLE device by any Smartphone and Tablet with BLE. Please may you double check your smartphone has BLE capability (Bluetooth Low Energy is available from Bluetooth 4.0 version)?

**Comment by teomaras76** [comment]
By the way, we started 2 weeks ago also an ST Community/Forum specific for Drone, you may eventually join it and post your questions also there:
https://community.st.com/community/drone-zone

**Comment by mrka124** [comment]
Thank you! This work for me :3

**Comment by teomaras76** [comment]
@dinhvankiet124  ok very good! So please kindly confirm, the binary file is working well, while if you try to compile the Truestudio project you have some issues? Or everything is ok now?

**Comment by mrka124** [comment]
Hi, my friend ungtu3012 confirm that worked. But when I chose Target > Program & Start, two LED at the top were blinking once and stop immediately. Then the android app can't find them.

Android app v29

**Comment by teomaras76** [comment]
Hi,
it's a very strange beahviour, if you download exactly same binary file ungtu3012 used (that I uploaded last week) it should work. Are you sure that battery is fully charged to 4.2V?
Even if the app is not yet connected to the FCU one LED should be still blinking.
I made simple video (not yet official one) at this link, please refer to it:
https://www.youtube.com/watch?v=RPNLA2R3kRo

have you downloaded the binary file using STLink Utility?
http://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-programmers/stsw-link007.html
