### ISSUE TITLE
Android app take off button missing?

### ISSUE THREAD

**Issue by mrka124** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#12]
I try to take off but not find take off button on Android app v29

**Comment by mrka124** [comment]
![30725562_1943972925675936_8939035675622113280_n](https://user-images.githubusercontent.com/19968582/39004548-cee89cba-4427-11e8-91bf-540fda10bd75.jpg)

**Comment by messinajo** [comment]
Something seems to be wrong in your interface. 
This should be the correct one:

![image](https://user-images.githubusercontent.com/29916569/39004948-0c88ef58-43ff-11e8-8484-e76090ed8c00.png)

**Comment by messinajo** [comment]
Did you use the apk or you use the source code?

**Comment by mrka124** [comment]
I use apk like your images! If you click on the bar after a joint stick, you will get my images

@messinajo  So what is your take off button?

**Comment by messinajo** [comment]
If you have armed the motor you only need to move the left slider (joystick) up. (living the interface as I show you)

**Comment by ungtu3012** [comment]
I already done it while "armed" button become green but nothing happen.
when i unplugged St-link V2 from board and even plugged battery into board, i couldn't connect BLE again.I and dingvankiet124 work together :")

Thanks for you support!!!

**Comment by messinajo** [comment]
Can your refer if you do exactly the following steps:
1) Without anything connected to the board, plug the battery connector (battery fully charged)
2) The two leds swith on, one with fixed light and one blinking.
3) from the app, connect through bluetooth to the board
4)  calibrate sensors (first button from left, in the last raw)
5)  arm the motors
6) push the left joystick cursor up.

That's all.

Let me know.

**Comment by mrka124** [comment]
1-2. There are 3 leds, 2 leds that you talk about not light. Only one led that far away on (with battery)

When disconnect STLINK, android app can't find board

**Comment by teomaras76** [comment]
Hi, I made simple video (not yet ST official one but temporary), please refer to it for the moment for BLE operation:
https://www.youtube.com/watch?v=RPNLA2R3kRo
