### ISSUE TITLE
External ESC 

### ISSUE THREAD

**Issue by KiranKanchi** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#13]
Hello, 
I read that some hardware changes are required to use fcu with external ESC.
Presence of MOSFET drivers at pwm out should not be a problem to external ESC right ? (We just have a larger current limit superficially). 
I wish there were schematics or videos of FCU with external esc of some 30A.
Thanks

**Comment by messinajo** [comment]
I replied to you on ST Drone-Zone Community.
http://community.st.com/community/drone-zone
