### ISSUE TITLE
App - Motors not armed

### ISSUE THREAD

**Issue by kylix34** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#2]
even if you arm the motors, in the app GUI you always see the "Not armed" red button.
It will be also useful to have an indicator of the battery voltage level.

**Comment by teomaras76** [comment]
Yes you are right, thanks a lot for your comment. BLE app is still in beta version and now we are focusing on fine tuning the Fw ( both on FCU and App side) to can fly the drone with BLE app with performance as much as possible to external mechanical remocon (that as now is the best for agility and manouvrability performance. We will release next week a new version with better performance and better stability for BLE connection.

We have already in plan in following weeks (or beg of next year) to enable in the FCU FW the feature to send several additional information:
- sensors value
- battery value
- arming status
-....

**Comment by teomaras76** [comment]
Please download newest version of FW project for BLE. New PID parameters solve an issue of drift at lift off.

**Comment by KiranKanchi** [comment]
source code for app will be published ?

**Comment by teomaras76** [comment]
Yes it will be published as soon as the revision will be a stable one, now it'a still in beta and under debugging so some parts may change.

**Comment by KiranKanchi** [comment]
Awesome :-) can we expect a few more video tutorials on YouTube?

**Comment by teomaras76** [comment]
Yes next video will be more focused on the FW project and use of the App

**Comment by kylix34** [comment]
Firmware updated but it still has a slight drift at lift off. I might need to better position the battery.

**Comment by KiranKanchi** [comment]
Kylix, are you using BLDC or DC motor setup ?

**Comment by kylix34** [comment]
DC motors (the ones from the kit). It would be nice to have a forum or something like this to talk, instead of Github.

**Comment by KiranKanchi** [comment]
True that, 8520 motors right ? Propeller 65mm ?
Could post a pic of your build please ?
Using Bluetooth app to control?

**Comment by kylix34** [comment]
Yes, 8520 motors and 65 mm propellers. I'm using my Android phone to control it but it's not easy :)
![24300941_1787314587959138_8452881842388865287_n](https://user-images.githubusercontent.com/13137515/34122830-f5e74e6a-e42d-11e7-9b38-87517587357f.jpg)
![24312949_1787314697959127_2209658583221074738_n](https://user-images.githubusercontent.com/13137515/34122831-f60eeefc-e42d-11e7-8e3a-ce235c4c6298.jpg)
![24775262_1787314491292481_5534614568348164708_n](https://user-images.githubusercontent.com/13137515/34122832-f634190c-e42d-11e7-85fa-68c1dd80ad22.jpg)
![24862241_1787314737959123_32374071336583423_n](https://user-images.githubusercontent.com/13137515/34122833-f65a5d56-e42d-11e7-83c1-78f05fc05c4c.jpg)

**Comment by KiranKanchi** [comment]
Wow, sweet build <3 did you print props too ?

**Comment by kylix34** [comment]
Nope, the propellers are standard ...

**Comment by teomaras76** [comment]
Yes next video will be more focused on the FW project and use of the App

**Comment by teomaras76** [comment]
Kylix, nice and ver clean built!
Yes we are going to have also a dedicated forum for it beginning of next year, now we are preparing the page.
A small drift at the lift off it's normal (I think you already did the sensor calibration procedure) and is related to the so-called "ground effect": when the drone is too close to ground, altitude less than 2-3 time size of diameter of drone, the air moved from propeller is not circulating smoothly and makes the drone control not easy.

**Comment by teomaras76** [comment]
Do you notice some drift also when you take the drone at more than 1m altitude?

**Comment by kylix34** [comment]
Hello Teo!
You are right, I'm noticing the drift only when the drone is lower than 20-30 cm to the ground.

**Comment by teomaras76** [comment]
Ok this is normal.  There is a ground effect, against with the drone is struggling to keep stable asset, and since with propeller guard is a little heavy it struggles for stability and there is higher vibration. After that altitude it becomes easier for the drone to have stable hovering.

**Comment by teomaras76** [comment]
At lift off you need to manually compensate a little, with mechanical remocon is easier and you can have a smooth lift off.

**Comment by teomaras76** [comment]
With BLE app actually you are not so fast to give commands to compensate so it's more difficult to lift off. When you can pass about 30cm threshold everything becomes easier.

**Comment by kylix34** [comment]
Thanks! Could you advice on a remocon/receiver model?

**Comment by teomaras76** [comment]
Sorry officially I cannot recommend a specific one... What I can say that Walkera Devo 7E with Deviation FW is cheap and I am using it for testing the minidrone successfully. Also small size and easy to carry on.

**Comment by teomaras76** [comment]
Hi !
Last week we opened a new community specific for Drone on ST website, please kindly have a look here:
https://community.st.com/community/drone-zone
It would be used also as a generic forum for Q&A both on ST FCU or ST ESC demo boards.
Also it would be very appreciated if you may share with other community users any photo or video of the minidrone you built with the ST FCU.
 
Matteo
