### ISSUE TITLE
Power failure

### ISSUE THREAD

**Issue by jaugu** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#5]

**Comment by teomaras76** [comment]
Hi !
Last week we opened a new community specific for Drone on ST website, please kindly have a look here:
https://community.st.com/community/drone-zone
It would be used also as a generic forum for Q&A both on ST FCU or ST ESC demo boards.
Also it would be very appreciated if you may share with other community users any photo or video of the minidrone you built with the ST FCU.
 
Matteo
