### ISSUE TITLE
Turning off the drone

### ISSUE THREAD

**Issue by ziogianni** [STMicroelectronics-CentralLabs/ST_Drone_FCU_F401#9]
Hello how can I turn off the board without disconnecting the battery every time? Have I overlooked any option in the appDrone? There's always a blinking LED...

**Comment by teomaras76** [comment]
Hi, sorry what do you mean by "turning off" the board? Please kindly explain more in details. The battery is connected to the Vbus on the board by HW, and also the STM32 is always connected, there is no HW switch option on the board.

You may turn off the LED by FW, but be careful that STM32 will continue to drain current from battery and you may risk to discharge it completely.
Disconnecting the battery is the safest operation in most of drones in the market as well, whenever there is not an HW switch.

**Comment by ziogianni** [comment]
Hi Matteo, yes I meant to say to turn off the Steval board, but you've
already answered. Thanks

Il 2 mar 2018 11:14 AM, "Matteo Maravita" <notifications@github.com> ha
scritto:

Hi, sorry what do you mean by "turning off" the board? Please kindly
explain more in details. The battery is connected to the Vbus on the board
by HW, and also the STM32 is always connected, there is no HW switch option
on the board.

You may turn off the LED by FW, but be careful that STM32 will continue to
drain current from battery and you may risk to discharge it completely.
Disconnecting the battery is the safest operation in most of drones in the
market as well, whenever there is not an HW switch.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/STMicroelectronics-CentralLabs/ST_Drone_FCU_F401/issues/9#issuecomment-369881117>,
or mute the thread

**Comment by teomaras76** [comment]
Hi !
Last week we opened a new community specific for Drone on ST website, please kindly have a look here:
https://community.st.com/community/drone-zone
It would be used also as a generic forum for Q&A both on ST FCU or ST ESC demo boards.
Also it would be very appreciated if you may share with other community users any photo or video of the minidrone you built with the ST FCU.
 
Matteo
